server:
  port: 8101
spring:
  application:
    name: consumer-user
eureka:
  instance:
    perfer-ip-address: true #注册服务时使用服务的IP地址
  client:
    #eureka注册中心地址
    service-url:
      defaultZone: http://192.168.1.2:8761/eureka/
