server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server   #eureka实例的主机名
  client:
    #不把自己注册到eureka上
    registerWithEureka: false
    #不从eureka上来获取服务的信息
    fetchRegistry: false
    #钟鼎eureka注册中心地址
    service-url:
      defaultZone: http://192.168.1.2:8761/eureka/
